language: node_js
node_js: node
sudo: false
cache: false

stages:
  - name: "application test & build"

jobs:
  include:
    - stage: "application test & build"
      name: "Team Chat Reference Application"
      before_install:
        - |
          echo '
          REACT_APP_PUBLISH_KEY="${DEV_PUBLISH_KEY}",
          REACT_APP_SUBSCRIBE_KEY="${DEV_SUBSCRIBE_KEY}"
          ' >> .env
      install:
        - npm install
      script:
        - npm run test
        - npm run build
